services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports: ["2181:2181"]
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports: ["9092:9092"]
    depends_on: [zookeeper]
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports: ["3306:3306"]
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: job_dw
    volumes: [mysql_data:/var/lib/mysql]

  spark:
    build: ./docker/spark
    container_name: spark
    ports: ["8080:8080", "7077:7077"]
    environment:
      SPARK_MODE: master
    volumes:
      - ./spark-apps:/opt/spark/apps

  spark-worker:
    build: ./docker/spark
    container_name: spark-worker
    depends_on: [spark]
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark:7077
    volumes:
      - ./spark-apps:/opt/spark/apps

  airflow:
    image: apache/airflow:2.10.0-python3.11
    container_name: airflow
    command: standalone
    ports: ["8081:8080"]
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    volumes: [./dags:/opt/airflow/dags]

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports: ["3000:3000"]
    volumes: [grafana_data:/var/lib/grafana]

volumes:
  mysql_data:
  grafana_data:
